### ISSUE TITLE
Selection bug!

### ISSUE THREAD

**Issue by jugsvn** [onegray/RadioButton-ios#1]
Hey there seems like a bug in the 

-(void) setSelected:(BOOL)selected method.

Instead of [rb super_setSelected:selected]; it should rather be [rb super_setSelected:NO];

**Comment by onegray** [comment]
Hm.. The idea is to automatically select another button when you deselect the current one.

**Comment by jugsvn** [comment]
Agreed. But when you try to deselect all the  buttons (when the screen loads or after data refresh), it will always select the first button by default.

So

[self.options[0] setSelected:NO];
[self.options[1] setSelected:NO];
[self.options[2] setSelected:NO];
[self.options[3] setSelected:NO];

will result in the first button being selected.

**Comment by onegray** [comment]
I've just added method 'deselectAllButtons' for this case.
Anyway, I agree the 'setSelected:NO' functionality is ambiguous if there are more then two buttons in the group.

**Comment by onegray** [comment]
I've updated the 'setSelected:' method.  Now the logic is following:
  If selected==YES, then it selects the button and deselects other buttons in the group.
  If selected==NO, then it deselects the button and if there are only two buttons in the group, then it selects second.

Thank you for the participation!

**Comment by jugsvn** [comment]
Awesome! Thanks mate!
