### ISSUE TITLE
How to setTitle for this custom?

### ISSUE THREAD

**Issue by duy84** [onegray/RadioButton-ios#3]
Hi guy,

I cannot setTitle for this custom button in my code.

How can I do that? Could you please explain more for us?

Thanks

**Comment by onegray** [comment]
Hi,
 just do it in the same way as for standard UIButton.
Here is an example how to create RadioButton programmatically:
 https://github.com/onegray/RadioButton-ios/blob/sample/ViewController.m#L34-L44
