### ISSUE TITLE
On selected radio button a blue image appears i don't know from where it is coming

### ISSUE THREAD

**Issue by qasimsqm** [onegray/RadioButton-ios#5]
![ios simulator screen shot 28 feb 2015 16 43 16](https://cloud.githubusercontent.com/assets/464520/6426066/ec834a78-bf68-11e4-8f97-f5ad70b314f1.png)
you can see there is a blue small rectangle on the op of selected image. How to remove it?

**Comment by onegray** [comment]
http://stackoverflow.com/questions/18923031/blue-box-showing-up-next-to-custom-uibutton-in-ios-app
