### ISSUE TITLE
deselect

### ISSUE THREAD

**Issue by 0xhex** [onegray/RadioButton-ios#7]
deselect is not active if you want deselect you should replace code with this

OLD CODE    -(void) onTouchUpInside
{
    [self setSelected:YES distinct:YES sendControlEvent:YES];
}

NEW CODE    -(void) onTouchUpInside
{
    [self setSelected:!self.selected distinct:YES sendControlEvent:YES];
}

**Comment by onegray** [comment]
Thanks, but I think it's a standard behaviour for radio button.
